pnpEnableEsmLoader: false

packageExtensions:
  "@yarnpkg/eslint-config@*":
    peerDependencies:
      eslint-plugin-arca: "*"
  tailwindcss-leading-trim@*:
    dependencies:
      postcss-selector-parser: "*"

yarnPath: .yarn/releases/yarn-sources.cjs
